import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { TopBar } from "@/components/topbar";
import { Footer } from "@/components/footer";

const geistSans = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "stem-ime",
  description: "Generated by stem-tech-team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <header>
          <TopBar />
        </header>

        {children}

        <footer >
            <Footer/>
        </footer>
      </body>
    </html>
  );
}
