import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TopBar } from "@/src/components/header";
import { Footer } from "@/src/components/footer";

const geistSans = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "stem-ime",
  description: "Generated by stem-tech-team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        id="topo"
        className={`${geistSans.className} min-h-screen antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <TopBar />
          <main className="flex flex-1 flex-col pt-20">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
